In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

import nltk
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow import keras
import seaborn as sns
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt

In [2]:
emotion_df=pd.read_csv('Emotions.csv')
violence_df=pd.read_csv('Violence.csv')
hate_df=pd.read_csv('Hatespeech.csv')

In [3]:
emotion_df.head()

Unnamed: 0                                               text  label
0           0      i just feel really helpless and heavy hearted      4
1           1  ive enjoyed being able to slouch about relax a...      0
2           2  i gave up my internship with the dmrg and am f...      4
3           3                         i dont know i feel so lost      0
4           4  i am a kindergarten teacher and i am thoroughl...      4

In [4]:
violence_df.head()

Tweet_ID                                              tweet  \
0  ID_0022DWKP  Had a dream i got raped last night. By a guy i...   
1  ID_00395QYM  he thought the word raped means sex and told m...   
2  ID_003EOSSF  She NOT TALKING TO ME I WAS RAPED BY 2 MEN 1 M...   
3  ID_004BBHOD  I was sexually abused for 3 years at age 4 to ...   
4  ID_004F7516  Chessy Prout can do better by telling the trut...   

              type  
0  sexual_violence  
1  sexual_violence  
2  sexual_violence  
3  sexual_violence  
4  sexual_violence

In [5]:
hate_df.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [6]:
emotion_df.drop(columns=['Unnamed: 0'], inplace=True)
violence_df.drop(columns=['Tweet_ID'], inplace=True)
hate_df=hate_df[['tweet','class']]

In [7]:
emotion_df.columns,violence_df.columns,hate_df.columns

(Index(['text', 'label'], dtype='object'),
 Index(['tweet', 'type'], dtype='object'),
 Index(['tweet', 'class'], dtype='object'))

In [8]:
violence_df.rename(columns={'tweet':'text','type':'label'},inplace=True)
hate_df.rename(columns={'tweet':'text','class':'label'},inplace=True)

In [9]:
emotion_df.columns,violence_df.columns,hate_df.columns

(Index(['text', 'label'], dtype='object'),
 Index(['text', 'label'], dtype='object'),
 Index(['text', 'label'], dtype='object'))

In [10]:
emotion_df.isna().sum(), violence_df.isna().sum(), hate_df.isna().sum()

(text     0
 label    0
 dtype: int64,
 text     0
 label    0
 dtype: int64,
 text     0
 label    0
 dtype: int64)

In [11]:
emotion_df.shape, violence_df.shape, hate_df.shape

((416809, 2), (39650, 2), (24783, 2))

In [12]:
emotion_df['label'].value_counts()

label
1    141067
0    121187
3     57317
4     47712
2     34554
5     14972
Name: count, dtype: int64

In [13]:
violence_df['label'].value_counts()

label
sexual_violence                 32648
Physical_violence                5946
emotional_violence                651
economic_violence                 217
Harmful_Traditional_practice      188
Name: count, dtype: int64

In [14]:
hate_df['label'].value_counts()

label
1    19190
2     4163
0     1430
Name: count, dtype: int64

In [15]:
e_df=pd.DataFrame()
for i in  range(len(emotion_df['label'].unique())):
    subset=emotion_df[emotion_df['label']==i].sample(n=2000,random_state=42)
    e_df=pd.concat([e_df,subset])

In [16]:
e_df.shape

(12000, 2)

In [17]:
emotion_df=e_df.copy()

In [18]:
emotion_df['label'].value_counts()

label
0    2000
1    2000
2    2000
3    2000
4    2000
5    2000
Name: count, dtype: int64

In [19]:
sexual_violence=violence_df[violence_df['label']=='sexual_violence'].sample(n=4998, random_state=42)
violence_df=violence_df[violence_df['label']!='sexual_violence']

In [20]:
violence_df=pd.concat([violence_df,sexual_violence], axis=0)

In [21]:
violence_df['label'].value_counts()

label
Physical_violence               5946
sexual_violence                 4998
emotional_violence               651
economic_violence                217
Harmful_Traditional_practice     188
Name: count, dtype: int64

In [22]:
offensive_speech=hate_df[hate_df['label']==1].sample(n=6407, random_state=42)
hate_df=hate_df[hate_df['label']!=1]

In [23]:
hate_df=pd.concat([offensive_speech,hate_df], axis=0)

In [24]:
hate_df['label'].value_counts()

label
1    6407
2    4163
0    1430
Name: count, dtype: int64

In [25]:
hate_df.shape,emotion_df.shape, violence_df.shape

((12000, 2), (12000, 2), (12000, 2))

In [26]:
label_encoder=LabelEncoder()
violence_df['label']=label_encoder.fit_transform(violence_df['label'])

In [27]:
violence_df

text  label
6      My Husband Beats Me Frequently, Wife Tells Cou...      1
29     Best thing for me to do, is remain silent when...      1
30     My husband will never beat me, Bambam denies r...      1
33     theyre like, i just wanna be a baby maker with...      1
35     I was in England for a week, the longest I’ve ...      1
...                                                  ...    ...
25368  i was 13 and had just been raped. the police t...      4
13942  So bad.She/he don't know how blessed they are ...      4
34704  I was Hide and he was Yoshi. We were Hideyoshi...      4
18626  It actually sickens me that he's so smug abt '...      4
36756  without any fear of being raped. Bcaz I know m...      4

[12000 rows x 2 columns]

In [28]:
violence_df['label'].unique()

array([1, 3, 0, 2, 4])

In [29]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ambik\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [30]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ambik\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ambik\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [31]:
stop_words=set(stopwords.words('english'))

In [32]:
len(stop_words)

179

In [33]:
def remove_stopwords(text):
    all_words=nltk.word_tokenize(text)
    filtered_words=[word for word in all_words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

In [34]:
emotion_df['text']=emotion_df['text'].apply(remove_stopwords)
violence_df['text']=violence_df['text'].apply(remove_stopwords)
hate_df['text']=hate_df['text'].apply(remove_stopwords)

In [35]:
emotion_df.head()

text  label
133243  ive learned surround women lift leave feeling ...      0
88501     already feel crappy upset situation doesnt help      0
131379  feel like lost mourned moved past tears relati...      0
148369  could write whole lot im feeling crappy dont t...      0
134438                        always seem feel inadequate      0

In [75]:
tokenizer=Tokenizer()

In [77]:
tokenizer.fit_on_texts(pd.concat([emotion_df['text'],violence_df['text'],hate_df['text']]))

In [81]:
emotion_sequence=tokenizer.texts_to_sequences(emotion_df['text'])
violence_sequence=tokenizer.texts_to_sequences(violence_df['text'])
hate_sequence=tokenizer.texts_to_sequences(hate_df['text'])

In [85]:
emotion_df['text'].iloc[2]

'feel like lost mourned moved past tears relationship'

In [87]:
emotion_sequence[2:3]

[[1, 5, 321, 11854, 1207, 422, 1093, 385]]

In [91]:
max_length=50
emotion_padded=pad_sequences(emotion_sequence,maxlen=max_length,padding='post')
violence_padded=pad_sequences(violence_sequence,maxlen=max_length,padding='post')
hate_padded=pad_sequences(hate_sequence,maxlen=max_length,padding='post')

In [93]:
emotion_padded[2:3]

array([[    1,     5,   321, 11854,  1207,   422,  1093,   385,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]])

In [95]:
emotion_labels=np.array(emotion_df['label'])
violence_labels=np.array(violence_df['label'])
hate_labels=np.array(hate_df['label'])

In [97]:
hate_labels

array([1, 1, 1, ..., 0, 2, 2], dtype=int64)

In [99]:
emotion_input_layer=keras.layers.Input(shape=(max_length,),name='emotion_input')
violence_input_layer=keras.layers.Input(shape=(max_length,),name='violence_input')
hate_input_layer=keras.layers.Input(shape=(max_length,),name='hate_input')

In [101]:
embedding_layer=keras.layers.Embedding(input_dim=len(tokenizer.word_index)+1,output_dim=128)

In [103]:
emotion_embedding=embedding_layer(emotion_input_layer)
violence_embedding=embedding_layer(violence_input_layer)
hate_embedding=embedding_layer(hate_input_layer)

In [110]:
shared_lstm=keras.layers.LSTM(64,return_sequences=True)